spring.application.name=PokemonWebApp
server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.web.resources.static-locations=classpath:/static/